apiVersion: v1
kind: Service
metadata:
  name: foo-app
  labels:
    app: foo-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: foo-app
  selector:
    app: foo-app

