apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: foo-app
  labels:
    app: foo-app
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: foo-app
    spec:
      containers:
        - name: foo-app
          image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
